# See https://gohugo.io/getting-started/configuration/

baseURL = "http://blog.itfuckenwimdy.cloud/congenial-parakeet/"
languageCode = "en-us"
title = "Today I Learned — Parakeet"

# Build static site to /docs folder so GitHub pages can serve it.
publishDir = "../docs"
             
# Serve statics from above Hugosite root.
staticDir = ["../static/"]

# Enable emoji
enableEmoji = true

# Use really small summaries...
summaryLength = 8

# Allow HTML to be used in articles.
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[module]
    [[module.mounts]]
        source = "../posts"
        target = "content/posts"
